#Minecraft server properties
#Sat Mar 14 14:15:58 UTC 2026
accepts-transfers=false
allow-flight=false
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
difficulty=normal
enable-command-block=true
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=true
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=4
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=leaves_us_in_peace\:wood_prevents_decay
initial-enabled-packs=vanilla,fabric,armor-stand-editor,babyfat,balm,biome_tag_villagers,blahaj,blockus,brewery,chalk,cinderscapes-common,computercraft,enderscape,explorify,extended_drawers,fabric-convention-tags-v2,farmersdelight,farmtweaks,friendsandfoes,glideaway,go-fish,illagerexp,jsonpatcher,kleeslabs,leaves_us_in_peace,lovely_snails,microfighters,mr_banner_text,mr_clifftree,mr_dungeons_andtaverns,mr_nightosphere,polychess,polydecorations,polydex,polyfactory,puddles,restart_detector,rocks,server_translations_api,simpleupdatechecker,simply-slingshot,sleepwarp,styledchat,televator,terrablender,terrestria-common,toms_mobs,trinkets,universal-graves,vaulted-end,woods_and_mires,enderscape\:fix_levitation_advancement,enderscape\:fix_vanilla_recipes,enderscape\:new_end_cities,enderscape\:new_terrain
level-name=world
level-seed=596054290122269981
level-type=minecraft\:normal
log-ips=true
max-chained-neighbor-updates=1000000
max-players=10
max-tick-time=60000
max-world-size=29999984
motd=dhpOS Server
network-compression-threshold=256
online-mode=false
op-permission-level=4
pause-when-empty-seconds=60
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
query.port=25565
rate-limit=0
rcon.password=
rcon.port=25575
region-file-compression=deflate
require-resource-pack=false
resource-pack=https\://poly-proxy-drab.vercel.app/polymania/music_rp+pack.zip
resource-pack-id=6953f0d8-fe52-495a-9960-e6203d087d82
resource-pack-prompt=This server uses resource pack to enhance gameplay with custom textures and models. It might be unplayable without them. Máy chủ này sử dụng gói tài nguyên để nâng cao trải nghiệm chơi game với các họa tiết và mô hình tùy chỉnh. Có thể sẽ không chơi được nếu thiếu chúng
resource-pack-sha1=
server-ip=
server-port=5610
simulation-distance=5
spawn-monsters=true
spawn-protection=0
sync-chunk-writes=true
text-filtering-config=
text-filtering-version=0
use-native-transport=true
view-distance=7
white-list=false
