#PlayerAbilityLib configuration file
#
#If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
#Mon Mar 09 20:45:07 ICT 2026
alwaysLogTamperWarnings=false
