#PlayerAbilityLib configuration file
#
#If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
#Thu Mar 12 13:49:41 UTC 2026
alwaysLogTamperWarnings=false
